name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write   # needed for pushing to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: reactapp/package-lock.json

      - name: Install deps
        working-directory: reactapp
        run: npm ci

      - name: Build
        working-directory: reactapp
        # CRA treats warnings as errors when CI=true; disable to allow deploys with warnings
        run: CI=false npm run build

      - name: Add CNAME (custom domain)
        working-directory: reactapp
        run: echo "michellef.dev" > build/CNAME

      - name: Configure Git identity (for gh-pages commit)
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Deploy to gh-pages
        working-directory: reactapp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          npx gh-pages -d build -b gh-pages --repo "$REPO_URL" -m "Deploy: ${{ github.sha }}"
