name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to push to gh-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (with cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: reactapp/package-lock.json  # <-- point to your lockfile

      - name: Install deps
        working-directory: reactapp
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build
        working-directory: reactapp
        run: CI=false npm run build

      - name: Add CNAME to build (custom domain)
        working-directory: reactapp
        run: echo "michellef.dev" > build/CNAME

      - name: Deploy to gh-pages
        working-directory: reactapp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx gh-pages -d build -b gh-pages
